ALTER TABLE auditoriaUsuario
MODIFY COLUMN accion ENUM(
  'CREACION',
  'ACTUALIZACION',
  'ELIMINACION',
  'DESACTIVACION',
  'ACTIVACION',
  'DUPLICADO',
  'ACTUALIZACION_DE_PERMISOS',
  'APROBAR_SOLICITUD',
  'DENEGAR_SOLICITUD',
  'ELIMINAR_SOLICITUD',
  'CREACION_SOLICITUD_MULTIMEDIA',
  'TRANSFERENCIA',
  'TRANSCENDIO'
) NOT NULL;