export enum AUDITORIAUSUARIO_ENUM {
  CREACION = "CREACION",
  ACTUALIZACION = "ACTUALIZACION",
  ELIMINACION = "ELIMINACION",
  DESACTIVACION = "DESACTIVACION",
  ACTIVACION = "ACTIVACION",
  ACTUALIZACION_DE_PERMISOS = "ACTUALIZACION_DE_PERMISOS",
}
