export enum ROLES {
  ADMINISTRADOR = "ADMINISTRADOR",
  SUPERVISOR = "SUPERVISOR",
  SUPERVISOR_LOCAL = "SUPERVISOR LOCAL",
  OBRERO_CIUDAD = "OBRERO_CIUDAD",
  OBRERO_CAMPO = "OBRERO CAMPO",
  MULTIMEDIA = "MULTIMEDIA",
  ADMINISTRADOR_MULTIMEDIA = "ADMINISTRADOR MULTIMEDIA",
  ASISTENTE_OOTS = "ASISTENTE OOTS",
}

export enum ROLES_ID {
  ADMINISTRADOR = "1",
  SUPERVISOR = "2",
  SUPERVISOR_LOCAL = "3",
  OBRERO_CIUDAD = "4",
  OBRERO_CAMPO = "5",
  MULTIMEDIA = "6",
  ADMINISTRADOR_MULTIMEDIA = "7",
  ASISTENTE_OOTS = "8",
}
