export enum ROLES {
  ADMINISTRADOR = "ADMINISTRADOR",
  SUPERVISOR = "SUPERVISOR",
  SUPERVISOR_LOCAL = "SUPERVISOR LOCAL",
  OBRERO_CIUDAD = "OBRERO_CIUDAD",
  OBRERO_CAMPO = "OBRERO CAMPO",
  MULTIMEDIA = "MULTIMEDIA",
  ASISTENTE_OOTS = "ASISTENTE OOTS",
  ADMINISTRADOR_MULTIMEDIA = "ADMINISTRADOR MULTIMEDIA",
  AYUDANTE = "AYUDANTE",
  APROBADOR_MULTIMEDIA = "APROBADOR MULTIMEDIA",
  COMITE_RECTOR = "COMITE RECTOR",
}

export enum ROLES_ID {
  ADMINISTRADOR = "1",
  SUPERVISOR = "2",
  SUPERVISOR_LOCAL = "3",
  OBRERO_CIUDAD = "4",
  OBRERO_CAMPO = "5",
  MULTIMEDIA = "6",
  ASISTENTE_OOTS = "8",
  ADMINISTRADOR_MULTIMEDIA = "9",
  AYUDANTE = "10",
  APROBADOR_MULTIMEDIA = "11",
  COMITE_RECTOR = "13",
}
